# Site settings
title: CaryC Blog
SEOTitle: 我的思想汇报 | CaryC Blog
header-img: img/home-bg.jpg
email: longlivewe@gmail.com
description: "关于生活与技术 | CaryC，Web，生活，分享 | 这里是 @CaryC 的个人博客，与你一起发现更大的世界。"
keyword: "CaryC, 技术, 生活, 分享, longlivewe , CaryC的博客, CaryC Blog, 博客, 个人网站, 互联网, Web, 有趣, 学习, 设计"
url: "https://longlivewe.github.io"              # your host, for absolute URL
baseurl: ""                             # for example, '/blog' if your blog hosted on 'host/blog'

# Publish posts or collection documents with a future date.
future: true

# SNS settings
RSS: false
weibo_username:     longlivewe
#zhihu_username:     huxpro
github_username:    longlivewe
twitter_username:   C_henX_i
facebook_username:  longlivewe
#linkedin_username:  陈-曦-iamcarychen



# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
highlighter: rouge
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md","README.zh.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`
# If you have timezone issue (e.g. #68) in China, uncomment to use this:
#timezone: CN



# Gems
# from PR#40, to support local preview for Jekyll 3.0
# make sure you have this gem installed
# `$ gem install jekyll-paginate`
plugins: [jekyll-paginate]



# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
kramdown:
  input: GFM                            # use Github Flavored Markdown !important
  syntax_highlighter_opts:
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1



# Disqus settings
#disqus_username: cary_c
#gitalk:
    owner: longlivewe
    repo: 我的思想汇报
    clientID: 1fc21e7b2bdce755ba86
    clientSecret: dd71abecbe99ec8c2f5f8c6d1bc4156025fea484
    admin: longlivewe

# Netease settings
netease_comment: false



# Analytics settings
# Baidu Analytics
# ba_track_id: [your track id]

# Google Analytics
ga_track_id: 'UA-164526860-1'            # Format: UA-xxxxxx-xx
ga_domain: wdsxhb.club



# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "For the next quantum leap<br>千万人，吾往矣"
sidebar-avatar: /img/1.jpg      # use absolute URL, seeing it's used in both `/` and `/about/`



# Featured Tags
featured-tags: true                     # whether or not using Feature-Tags
featured-condition-size: 1              # A tag will be featured if the size of it is more than this condition value



# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true



# MathJax rendering for layout:page (e.g. post preview)
page-mathjax: false



# Friends
friends: [
    {

        title: "方寸间",
        href: "https://10101.io/"
    #},{
    #    title: "Sherry Wu",
    #    href: "https://xuechundesign.github.io"
    },{
        title: "ChrAlpha 的幻想乡",
        href: "https://blog.ichr.me/"
    },{
        title: "Mmx's Blog",
        href: "https://spmax.top/"
    },{
        title: "豆瓣",
        href: "https://www.douban.com"
    #},{
    #    title: "JiyinYiyong",
    #    href: "http://tiye.me/"
   # },{
   #     title: "David's Game",
   #     href: "https://www.ruoyaowu.com/"
   # },{
   #     title: "DHong Say",
   #     href: "http://dhong.co"
    },{
        title: "安卓",
        href: "https://www.android.com/"
    }
]
